Danashi/adminprofile-information
calblueprint/sundayfriends pull request #18
Opened 2021-10-08 09:46 UTC by danashimessele

Created the components for about info and contact info and started a little bit of styling. Have not uploaded dummy data to the backend yet. Currently trying to center everything on the page and get the right styling for the title, name, headers, etc., and link to global styling to sync with the rest of the website. 

## Related PRs

_Optional - any related PRs you're waiting on, or PRs that will conflict, etc_

## Screenshots

![sprinttask2](https://user-images.githubusercontent.com/90217967/136535210-e1a50326-4148-47b9-b0fe-8ba9f0e462cd.png)

CC: @gabriel-jt @cindyxzhang

2021-10-10 22:05 UTC, gabriel-jt commented on pages/Profile/Profile.module.css
> +.all {
nit: please fix the spacing within the `.all` CSS rule

2021-10-10 22:07 UTC, gabriel-jt commented on pages/Profile/index.tsx
> +        <body className = {styles.body}>
Wrapping the Layout component within the `body` tag shouldn't be necessary. We will work on styling this Layout component more!

2021-10-10 22:14 UTC, gabriel-jt commented on pages/Profile/index.tsx
> +                        <div className = {styles.box}>
You should the code within the `div` styled with `styles.box` its own component within the `components` folder. We want to make front-end components that are reusable/modularized. Another possibility, is also just using the Material UI [Card](https://mui.com/components/cards/) component. Let me know if you need help with any of this or if you have any questions!

2021-10-14 10:38 UTC, danashimessele commented
> Also, a few more things I wanted to address.
> 
> * Could you please pull `main` and fix the merge conflicts then re-request review?
> * Please send me an updated screenshot of the Profile page after you pull main. I'd like to see if the font got applied to your components/text

![image](https://user-images.githubusercontent.com/90217967/137301897-7e8a4a65-f017-49f9-885f-bf284c2c2756.png)

2021-10-15 03:38 UTC, gabriel-jt commented on components/ProfileInfo/AboutInfo.tsx
> +    last_active: string,
for variable names and JSON attribute names, let's stick to using camel case convention within our TS/JS files
```suggestion
    lastActive: string,
```

2021-10-15 03:39 UTC, gabriel-jt commented on pages/EditProfile/index.tsx
> +import React from 'react';
I don't think we will need an EditProfile page since we want in-line editing. Please delete this file.

2021-10-15 03:40 UTC, gabriel-jt commented on pages/Profile/index.tsx
> +                    <Button className={styles.button} onClick={() => {router.push(`./EditProfile`);}}>Edit</Button>
Since we will be deleting the edit profile page, just make sure this button does not route to /EditProfile

2021-10-15 03:44 UTC, gabriel-jt commented on pages/Profile/Profile.module.css
> +    background-color: #253C85;
With hard-coded hex colors, if they don't exist within the global.css file, just add them in there and use the color in your css as `var(--your-color)`. This allows you to reuse the colors in other css files and you'll only have to change the hex code in one file!

2021-10-15 03:49 UTC, gabriel-jt requested changes
Great progress on this PR Danashi! Just a few more fixes, which are described in more detail in my previous comments. I also noticed that the text font is not consistent (this is something I probably can fix/will have to do, but let me know if you'd like to help!)

2021-10-15 06:20 UTC, danashimessele commented on components/ProfileInfo/AboutInfo.tsx
> +                <div><Typography variant="subtitle1" fontWeight="bold">ROLE</Typography></div>
Yes, I had to do that to style the information in the box with flex and space-between

2021-10-30 18:49 UTC, gabriel-jt commented on pages/profile/index.tsx
> +                    <div className={styles.h1}> Cindo Zhang </div>
use an h1 element here instead of a div styled with `styles.h1`

2021-10-30 18:55 UTC, gabriel-jt commented
PR is looking good! Just fix the top spacing for the profile page (I think there is too much space). Also, remove the hover state for the edit button for now (kelly is making it and I don't think it should be white)
<img width="1557" alt="Screen Shot 2021-10-30 at 11 44 10 AM" src="https://user-images.githubusercontent.com/28970991/139555298-e1a846ef-c033-408f-a107-a4b945172b2d.png">

2021-10-30 23:34 UTC, gabriel-jt approved these changes
LGTM!

2021-10-30 23:38 UTC, merged