Gabe/firebase-auth
calblueprint/sundayfriends pull request #24
Opened 2021-10-28 09:31 UTC by gabriel-jt

Added a basic login screen, implemented user auth, created protected routes, and verified that a logged-in user is an admin.

Updates to latest commits:
- Used Server Side Rendering to load admin data before client loads pages (prevents non-admin users from getting previews of protected routes and allows pages to properly load)
- Fixed the refreshing issue! (no longer logged out after one refresh)
- Refactored code and simplified our auth firebase lib/utility functions
- Used cookies/tokens to keep track if user has already signed in

## Testing Done (Manual)
- Navigated to every protected route (users, transactions, admins, profile) with a valid admin user and made sure I could access those pages.
- Refreshed at every protected route while logged in as an admin and made sure admin was not logged out
- Attempted to log in with non-admin credentials (ordinary user) and made sure error messages appeared on the console
- Attempted to navigate to `localhost:3000/{route}` where route is every protected route while logged out and made sure I was redirected back to the sign in page.
- Checked that unsuccessful attempts to log in cleared the sign in form

## Affected PRs
Any PR that needs admin credentials/information will now be able to!

## Screenshots

![Screen Shot 2021-10-28 at 2 31 05 AM](https://user-images.githubusercontent.com/28970991/139228961-78426af4-83e1-4458-88f4-61f9a1e7b72d.png)

CC: @cindyxzhang

2021-10-29 21:09 UTC, jacobjk01 commented
Refreshing the page signs me out! plz check and see if that's what happens for u too

2021-10-29 21:58 UTC, sydbui requested changes
It signs out when you refresh or even if it is a browser refresh which is pretty buggy. Also idk if this is from the auth but the transaction page looks like this for me
<img width="1440" alt="Screen Shot 2021-10-29 at 2 57 20 PM" src="https://user-images.githubusercontent.com/57571626/139505944-f4b2f6da-36c5-4232-aca8-7f65ad13c951.png">

2021-10-29 21:58 UTC, sydbui commented on firebase/auth/auth.tsx
> +export const signInWithEmailAndPassword = async (email: string, password: string) => {
add return type for typescript

2021-10-29 21:58 UTC, sydbui commented on firebase/auth/auth.tsx
> +export const registerWithEmailAndPassword = async (email: string, password: string) => {
return type

2021-10-29 21:58 UTC, sydbui commented on firebase/auth/auth.tsx
> +const useFirebaseAuth = () => {
return type

2021-10-29 21:58 UTC, sydbui commented on firebase/auth/useAuth.tsx
> +export const useAuth = () => useContext(authUserContext);
return type

2021-10-29 21:58 UTC, sydbui commented on firebase/auth/useAuth.tsx
> +const AuthUserProvider: React.FunctionComponent = ({ children }) => {
props validation

2021-11-04 08:05 UTC, cindyxzhang requested changes
Not sure why but I get logged out when I press on the Sunday Friends text on the nav bar - I don't think this is expected behaviour for when I am logged in.

2021-11-04 08:09 UTC, gabriel-jt commented
> Not sure why but I get logged out when I press on the Sunday Friends text on the nav bar - I don't think this is expected behaviour for when I am logged in.

I don't think you're actually logged out, I believe clicking the Sunday Friends text redirects you back to the sign in page, but you're still logged in. I believe Danashi will fix this in his nav bar PR? (making it so that the logo/sunday friends text will not navigate you back to the sign in page).

2021-11-04 08:11 UTC, cindyxzhang commented
> It signs out when you refresh or even if it is a browser refresh which is pretty buggy. Also idk if this is from the auth but the transaction page looks like this for me <img alt="Screen Shot 2021-10-29 at 2 57 20 PM" width="1440" src="https://user-images.githubusercontent.com/57571626/139505944-f4b2f6da-36c5-4232-aca8-7f65ad13c951.png">

also still getting this bug on most recent commit. I'm also getting these errors in console (I know it's not the most recent version of Jacob's work) but could it be because of this? or is this auth related @jacobjk01 
![image](https://user-images.githubusercontent.com/61183011/140279152-148fbc45-f6de-4bec-8259-bf1f3bee7efa.png)

2021-11-04 08:12 UTC, gabriel-jt commented
@cindyxzhang I will add checks to redirect people who've already signed in back to transactions if they go back to the landing page

2021-11-04 08:16 UTC, gabriel-jt commented
> also still getting this bug on most recent commit. I'm also getting these errors in console (I know it's not the most recent version of Jacob's work) but could it be because of this? or is this auth related @jacobjk01

@cindyxzhang I think it potentially might be coming from the transactions table. I believe some keys are not unique since a transaction item has the username as its key (which is not gonna be unique to every transaction) @jacobjk01 could you look into this for your current PR?

2021-11-04 08:18 UTC, gabriel-jt commented
> > It signs out when you refresh or even if it is a browser refresh which is pretty buggy. Also idk if this is from the auth but the transaction page looks like this for me <img alt="Screen Shot 2021-10-29 at 2 57 20 PM" width="1440" src="https://user-images.githubusercontent.com/57571626/139505944-f4b2f6da-36c5-4232-aca8-7f65ad13c951.png">
> 
> also still getting this bug on most recent commit. I'm also getting these errors in console (I know it's not the most recent version of Jacob's work) but could it be because of this? or is this auth related @jacobjk01 ![image](https://user-images.githubusercontent.com/61183011/140279152-148fbc45-f6de-4bec-8259-bf1f3bee7efa.png)

Hmmm I don't think this is coming from auth... the other pages load fine for me and I no longer see this bug on my end. What exactly did you do? I wanna see if I can reproduce this bug

2021-11-05 04:01 UTC, cindyxzhang approved these changes
LGTM

2021-11-05 05:26 UTC, merged