Danashi/stylingnavbar
calblueprint/sundayfriends pull request #27
Opened 2021-10-30 22:54 UTC by danashimessele

Styling the navbar to match figma, added icons and spacing

## Related PRs

Adminprofile-information not merged yet, worked on separate branch

## Screenshots

![image](https://user-images.githubusercontent.com/90217967/139560627-d73bbff3-c4e5-47be-a1a2-aead97ee190d.png)

CC: @gabriel-jt @cindyxzhang

2021-11-04 00:07 UTC, gabriel-jt commented on components/Layout/SideNavbar/SideNavbar.tsx
>            onClick={() => {
Could you remove the onClick function for the Sunday Friends logo? I think we agreed on that the logo should not link you anywhere

2021-11-04 07:10 UTC, gabriel-jt commented on components/ProfileInfo/ProfileInfo.module.css
> +.fields {
Hmm I don't know why this CSS rule got duplicated here since I think you deleted last time, but could you please delete?

2021-11-04 07:10 UTC, gabriel-jt commented
Hey Danashi, could you please fix all merge conflicts/pull main again?

2021-11-04 07:11 UTC, gabriel-jt requested changes
LGTM! Just the few fixes I mentioned and resolve merge conflicts. Ping me again after you've done this, and I'll approve.

2021-11-05 03:47 UTC, cindyxzhang approved these changes
LGTM

2021-11-05 03:48 UTC, gabriel-jt approved these changes

2021-11-05 03:48 UTC, merged