User Account and Family Connect Backend
calblueprint/sundayfriends pull request #28
Opened 2021-10-30 23:43 UTC by sydbui

Get Live data for user and families 

## Related PRs

_Optional - any related PRs you're waiting on, or PRs that will conflict, etc_

## Screenshots

<img width="1253" alt="Screen Shot 2021-10-30 at 4 42 51 PM" src="https://user-images.githubusercontent.com/57571626/139561306-6d31b7ff-b461-42e9-ada7-012cdacf4655.png">

CC: @gabriel-jt @cindyxzhang

2021-11-04 07:20 UTC, gabriel-jt commented on pages/users/index.tsx
> +  useEffect(() => {
Could you look into using getServerSideProps/SSR (https://nextjs.org/docs/basic-features/data-fetching) to load the families for the users page? I have the same thoughts on scalability/response time for this page that I had with Jacob's latest PR. I have an example of this in my auth PR as well.

2021-11-04 07:26 UTC, gabriel-jt commented
<img width="1256" alt="Screen Shot 2021-11-04 at 12 22 26 AM" src="https://user-images.githubusercontent.com/28970991/140273524-3e1c93a8-9f55-49a4-b24e-e086c9c47278.png">
I am not sure if this is just happening on my end again, but when I shrink the window, the spacing between the manage buttons look a bit off. Does this also happen on your end? @cindyxzhang @jacobjk01 could y'all check as well?

2021-11-04 07:33 UTC, gabriel-jt requested changes
Great progress Syd!! Just take a look at/address my feedback

2021-11-04 23:29 UTC, cindyxzhang requested changes
![image](https://user-images.githubusercontent.com/61183011/140434036-c43a3f38-ca5d-4ad0-88fc-64df1922d3f0.png)

The scrolling part for the transactions is too small. Let's make the the whole modal scroll down! Can show you what I mean at worksesh

2021-11-08 07:06 UTC, gabriel-jt approved these changes
LGTM! awesome job syd

2021-11-08 21:57 UTC, merged